/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { RegisterListRelationFilter } from "../../register/base/RegisterListRelationFilter";
import { ScannedListRelationFilter } from "../../scanned/base/ScannedListRelationFilter";

@InputType()
class QrCodeWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  code?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isScanned?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RegisterListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RegisterListRelationFilter)
  @IsOptional()
  @Field(() => RegisterListRelationFilter, {
    nullable: true,
  })
  registers?: RegisterListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ScannedListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScannedListRelationFilter)
  @IsOptional()
  @Field(() => ScannedListRelationFilter, {
    nullable: true,
  })
  scanneds?: ScannedListRelationFilter;
}

export { QrCodeWhereInput as QrCodeWhereInput };
